# Generated by Django 3.1.6 on 2022-05-01 01:41

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220320_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
